# Generated by Django 6.0.3 on 2026-03-19 19:03

from django.db import migrations, models


def transfer_priority_to_importance(apps, schema_editor):
    Todo = apps.get_model("todos", "Todo")

    mapping = {1: "LOW", 2: "MEDIUM", 3: "HIGH"}

    for todo in Todo.objects.all():
        if hasattr(todo, "priority") and todo.priority is not None:
            todo.importance = mapping[todo.priority]
            todo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_person_todo_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="importance",
            field=models.CharField(
                blank=True,
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                null=True,
            ),
        ),
        migrations.RunPython(
            transfer_priority_to_importance, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="todo",
            name="priority",
        ),
    ]
